#! /bin/sh

bspc config border_width        3
bspc config window_gap         50

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config active_border_color "#de9043"
bspc config focused_border_color "#ebbb8c"
bspc config presel_border_color "#8cbbeb"
bspc config urgent_border_color "#00ffff"
bspc config focused_locked_border_color "#ff00ff"

bspc config normal_frame_opacity  0.0
bspc config focused_frame_opacity 1.0

bspc monitor VGA-0 -d 1 2 3
bspc monitor VGA-1 -d 4 5 6

xrandr --output VGA-1 --right-of VGA-0

feh --bg-center ~/wallpapers/minimalistic-city-digital-art-artwork_1280x1024.jpg &

panel &
