#! /bin/sh

bspc config border_width        3
bspc config window_gap         24

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config active_border_color "#3F4B9C"
bspc config focused_border_color "#3F4B9C"
bspc config presel_border_color "#181818"
bspc config urgent_border_color "#C90515"
bspc config focused_locked_border_color "#8C644C"

bspc config normal_frame_opacity  0.0
bspc config focused_frame_opacity 1.0

bspc monitor VGA-0 -d 1 2 3
bspc monitor VGA-1 -d 4 5 6


xrandr --output VGA-1 --right-of VGA-0
feh --bg-center ~/linuxpron/wallpapers/green-nebula.jpg &

panel &
