#! /bin/sh

bspc config border_width        1
bspc config window_gap          6
bspc config split_ratio         0.52

bspc config click_to_focus        true
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     true

#bspc config active_border_color       "#de9043"
bspc config focused_border_color        "#FF9999"
bspc config presel_border_color         "#6699CC"
bspc config urgent_border_color         "#00ffff"
bspc config focused_locked_border_color "#ff00ff"
bspc config normal_frame_opacity        0.0
bspc config focused_frame_opacity       1.0

bspc config -m HDMI-0 top_padding $PANEL_HEIGHT


bspc monitor HDMI-0 -d bridge holodeck science 10forward

#bspc rule -a smplayer split_ratio=0.75

compton &

xrdb load ~/.Xresources
xsetroot -cursor_name left_ptr

panel &
bg4desktop
