#! /bin/sh

bspc config border_width        1
bspc config window_gap         15

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     true


#bspc config active_border_color   "#de9043"
bspc config focused_border_color   "#FF9999"
bspc config presel_border_color    "#6699CC"
#bspc config urgent_border_color "#00ffff"
#bspc config focused_locked_border_color "#ff00ff"

bspc config normal_frame_opacity  0.0
bspc config focused_frame_opacity 1.0

xrdb load ~/.Xresources
xrandr --output DP-2 --right-of DP-1

bspc config -m DP-2 top_padding 0

bspc monitor DP-1 -d CONN DMX OraTDS
bspc monitor DP-2 -d ScienceStation WebMail HoloDeck

compton &
feh --bg-center ~/wallpapers/landscapes_outer_space.jpg &
panel &

